version: "3.8"

services:
  traefik:
    image: traefik:v2.0
    ports:
      - target: 80
        published: 80
        mode: host
      - target: 443
        published: 443
        mode: host
      - target: 5000
        published: 5000
        mode: host
    volumes:
    - /var/run/docker.sock:/var/run/docker.sock
    - public-certificates:/certificates
    environment:
      TZ: ${TIMEZONE:-America/Sao_Paulo}
    deploy:
      placement:
        constraints:
          - node.role == manager
      labels:
        - traefik.enable=true
        - traefik.docker.network=public

        - traefik.http.middlewares.https-redirect.redirectscheme.scheme=https
        - traefik.http.middlewares.https-redirect.redirectscheme.permanent=true

        - traefik.http.routers.router-http.rule=Host(`${TRAEFIK_SUBDOMAIN:-router}.${CLUSTER_DOMAIN:-localhost}`)
        - traefik.http.routers.router-http.entrypoints=http
        - traefik.http.routers.router-http.middlewares=https-redirect
        - traefik.http.routers.router-http.service=api@internal

        - traefik.http.routers.router-https.rule=Host(`${TRAEFIK_SUBDOMAIN:-router}.${CLUSTER_DOMAIN:-localhost}`)
        - traefik.http.routers.router-https.entrypoints=https
        - traefik.http.routers.router-https.tls=true
        - traefik.http.routers.router-https.service=api@internal
        - traefik.http.routers.router-https.tls.certresolver=le

        - traefik.http.services.router.loadbalancer.server.port=8080
    command:
      - --providers.docker=true
      - --providers.docker.exposedbydefault=false
      - --providers.docker.swarmmode=true
      - --entrypoints.http.address=:80
      - --entrypoints.https.address=:443
      - --entrypoints.registry.address=:5000
      - --certificatesresolvers.le.acme.email=${SSL_EMAIL:-pedrogabriel.delarosa@gmail.com}
      - --certificatesresolvers.le.acme.storage=/certificates/acme.json
      - --certificatesresolvers.le.acme.tlschallenge=true
      - --accesslog
      - --log
      - --api
    networks:
      - public

volumes:
  public-certificates:

networks:
  public:
    name: "public"
    external: false
