version: "3.6"

networks:
  agent_network:
    name: agent_network
    driver: overlay
    attachable: true
  
services:
  agent:
    image: portainer/agent:2.19.1
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /var/lib/docker/volumes:/var/lib/docker/volumes
    networks:
      - agent_network
    deploy:
      mode: global
      placement:
        constraints: 
          - node.platform.os == linux

  portainer:
    image: portainer/portainer-ce:latest
    command: -H tcp://tasks.agent:9001 --tlsskipverify
    networks:
      - agent_network
    ports:
      - "${PORTAINER_PORT?}:9000"
    environment:
      - TZ=${TZ?}
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro # Use Docker Socket Proxy and comment this line out, for improved security.
      - ${DOCKER_DATA_PATH}/portainer:/data # Change to local directory if you want to save/transfer config locally.
    deploy:
      mode: replicated
      replicas: 1
      restart_policy:
        condition: on-failure

      