version: "3"

networks:
  gitea:
    external: false
  public:
    external: true

volumes:
  gitea_data:
  gitea_postgres:

services:
  gitea:
    image: gitea/gitea:latest
    container_name: gitea
    environment:
      - USER_UID=1000
      - USER_GID=1000
      - GITEA__database__DB_TYPE=postgres
      - GITEA__database__HOST=postgres:5432
      - GITEA__database__NAME=gitea_db
      - GITEA__database__USER=gitea_db_user
      - GITEA__database__PASSWD=DB_PASSWORD
    networks:
      - gitea
      - public
    volumes:
      - gitea_data:/data
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
    depends_on:
      - postgres
    deploy:
      mode: replicated
      replicas: 1
      labels:
        - "traefik.enable=true" 
        - "traefik.docker.network=public"
        - "traefik.http.routers.gitea-https.rule=Host(`gitea.example.com`)" 
        - "traefik.http.routers.gitea-https.entrypoints=https" 
        - "traefik.http.routers.gitea-https.tls=true" 
        - "traefik.http.routers.gitea-https.service=gitea"
        - "traefik.http.services.gitea.loadbalancer.server.port=3000"

        - "traefik.tcp.routers.gitea-ssh.rule=HostSNI(`*`)"
        - "traefik.tcp.routers.gitea-ssh.entrypoints=ssh"
        - "traefik.tcp.routers.gitea-ssh.service=gitea-ssh-svc"
        - "traefik.tcp.services.gitea-ssh-svc.loadbalancer.server.port=22"
  postgres:
    image: postgres:16
    container_name: postgres_gitea
    environment:
       - POSTGRES_USER=gitea_db_user
       - POSTGRES_PASSWORD=DB_PASSWORD
       - POSTGRES_DB=gitea_db
    networks:
       - gitea
    volumes:
       - gitea_postgres:/var/lib/postgresql/data
       - /etc/timezone:/etc/timezone:ro
       - /etc/localtime:/etc/localtime:ro
    deploy:
      mode: replicated
      replicas: 1