version: '3.7'

# #################################################################################################
# Kafka + Zookeeper
# #################################################################################################
services:

  zookeeper:
    image: bitnami/zookeeper:latest
    # ports:
    #   - 2181:2181
    environment:
      ALLOW_ANONYMOUS_LOGIN: "yes"
    networks:
      - kafka

  kafka:
    image: bitnami/kafka:latest
    # ports:
    #   - 9092:9092
    environment:
      KAFKA_CFG_ZOOKEEPER_CONNECT: "zookeeper:2181"
      KAFKA_CFG_ADVERTISED_LISTENERS: "PLAINTEXT://localhost:9092"
      ALLOW_PLAINTEXT_LISTENER: "yes"
      KAFKA_OPTS: "-Dlog4j.rootLogger=WARN"
    networks:
      - kafka
    deploy:
      labels:
        # Traefik
        - "traefik.enable=true"
        - "traefik.http.services.kafka.loadbalancer.server.port=9092"
        - "traefik.http.middlewares.kafka-redirect.redirectscheme.scheme=https"
        # HTTP Router
        - "traefik.http.routers.kafka.entrypoints=web"
        - "traefik.http.routers.kafka.rule=Host(`${KAFKA_DOMAIN}`)"
        - "traefik.http.routers.kafka.middlewares=kafka-redirect"
        # HTTPS Router
        - "traefik.http.routers.kafka-secure.rule=Host(`${KAFKA_DOMAIN}`)"
        - "traefik.http.routers.kafka-secure.entrypoints=websecure"
        - "traefik.http.routers.kafka-secure.tls.certresolver=leresolver"

# #################################################################################################
# Networks
# #################################################################################################
networks:
  kafka:
