version: "3.1"
services:
    sftp:
      build: 
        context: .
      container_name: sftp_server
      working_dir: /app
      restart: always
      ports:
        - "2222:22"
      volumes:
        - /etc/localtime:/etc/localtime:ro
        - ./data/users.conf:/etc/sftp/users.conf:ro
        - ./data/home:/home