version: "3.1"
services:
    splunk:
      image: splunk/splunk:8.1.0
      container_name: splunk-8-1-0
      restart: always
      ports:
        - 127.0.0.1:5000:8000
        - 127.0.0.1:5001:8088
      environment:
        - SPLUNK_START_ARGS="--accept-license --answer-yes"
        - SPLUNK_PASSWORD=${DEFAULT_PASSWORD:-P@ssw0rdD5}
        - SPLUNK_LICENSE_URI="Free"
      volumes:
        - ./data/splunk/etc:/opt/splunk/etc
        - ./data/splunk/var:/opt/splunk/var
