version: '3'
services:
  web:
    image: gitlab/gitlab-ce:15.3.3-ce.0
    restart: always
    hostname: 'gitlab.example.com'
    environment:
      GITLAB_OMNIBUS_CONFIG: |
        external_url 'https://gitlab.example.com'
        # Add any other gitlab.rb configuration (https://gitlab.com/gitlab-org/omnibus-gitlab/blob/master/files/gitlab-config-template/gitlab.rb.template)
        gitlab_rails['time_zone']='Europe/Kiev'
        gitlab_rails['gitlab_default_can_create_group'] = true
        gitlab_rails['gitlab_username_changing_enabled'] = true
        gitlab_rails['lfs_enabled'] = true
        nginx['redirect_http_to_https'] = true
        gitlab_rails['gitlab_shell_ssh_port'] = 22222
        gitlab_rails['initial_root_password'] = "rootpass"
        allow_username_or_email_login = false
        gitlab_rails['ldap_enabled'] = true
        gitlab_rails['ldap_servers'] = {
        'main' =>
         {
         'label' => 'GitLab AD',
         'host' =>  'dc.example.com',
         'port' => '389',
         'uid' => 'sAMAccountName',
         'encryption' => 'plain',
         'bind_dn' => 'example\git',
         'password' => 'Passgit',
         'active_directory' => 'true',
         'timeout' => '10',
         'base' => 'DC=example,DC=com',
         'user_filter'=>'(&(objectClass=user)(memberOf=cn=AG_Git_Users,ou=GitLab,ou=Service-Accounts,dc=example,dc=com))'
         }
        }
        nginx['ssl_client_certificate'] = "/etc/gitlab/ssl/ca.crt"
        nginx['ssl_certificate'] = "/etc/gitlab/ssl/gitlab.example.com.crt"
        nginx['ssl_certificate_key'] = "/etc/gitlab/ssl/gitlab.example.com.key"
        nginx['ssl_verify_client'] = "off"
    ports:
      - '80:80'
      - '443:443'
      - '22222:22'
    volumes:
      - ./{{ docker_gitlab_host }}.crt:/etc/gitlab/ssl/gitlab.example.com.crt
      - ./{{ docker_gitlab_host }}.key:/etc/gitlab/ssl/gitlab.example.com.key
      - './data/config:/etc/gitlab'
      - './data/logs:/var/log/gitlab'
      - './data/opt:/var/opt/gitlab'

