version: "3.1"
services:
  mongodb:
    image: mongo:5.0.10
    restart: always
    container_name: ${ZONE}-mongo
    command: mongod --logpath=/dev/null --wiredTigerCacheSizeGB 1
    ports:
      - 37017:27017
    environment:
      MONGO_DATA_DIR: /data/db
      MONGO_LOG_DIR: /dev/null
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_ROOT_USERNAME:-root}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_ROOT_PASSWORD:-Passw0rd@57}
      MONGO_INITDB_DATABASE: "mdb1"
    volumes:
      - /etc/timezone:/etc/timezone:ro
      - /usr/share/zoneinfo/Europe/Kiev:/etc/localtime:ro
      - /backup:/backup
      - ./tools:/tools
      - ./data/mongo:/data/db
    #        - ./data/mongo.init:/docker-entrypoint-initdb.d
