services:
    elasticsearch:
        image: docker.elastic.co/elasticsearch/elasticsearch:8.13.4
        restart: on-failure
        mem_limit: 1g
        environment:
          - discovery.type=single-node                  # single-node cluster
          - xpack.security.enabled=false                # disable password security
          - xpack.security.http.ssl.enabled=false       # disable tls/ssl encryption
          - xpack.security.transport.ssl.enabled=false  # disable tls/ssl encryption
          - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
        ports:
          - 9200:9200
        volumes:
          - ./data/elasticsearch:/usr/share/elasticsearch/data
        networks:
          - local
        depends_on:
          - fluent-bit
        logging:
          driver: fluentd
          options:
            tag: efk.es
    kibana:
        image: docker.elastic.co/kibana/kibana:8.13.4
        restart: on-failure
        mem_limit: 1g
        environment:
          - ELASTICSEARCH_HOSTS=http://elasticsearch:9200
          - SERVER_HEAP_SIZE=512mm
        ports:
          - 5601:5601
        networks:
          - local
        depends_on:
          - fluent-bit
          - elasticsearch
        logging:
          driver: fluentd
          options:
            tag: efk.kibana
    fluent-bit:
        image: fluent/fluent-bit:1.8
        command:
          - /fluent-bit/bin/fluent-bit
          - --config=/etc/fluent-bit/fluent-bit.conf
        environment:
          - FLB_ES_HOST=elasticsearch
          - FLB_ES_PORT=9200
        ports:
          #- 2020:2020
          - 24224:24224
        volumes:
          - ./conf/:/etc/fluent-bit/:ro
        networks:
          - local
        logging:
          driver: fluentd
          options:
            tag: efk.fluent-bit
networks:
  local:
    driver: bridge
