version: '3'
services:
  shardsvr1_1:
    container_name: shardsvr1_1
    image: mongo:7.0.4
    restart: always
    command: mongod --auth --replSet shard1_rs --config /etc/mongod.conf
    environment:
      MONGO_DATA_DIR: /data/db
      MONGO_LOG_DIR: /dev/null
    ports:
      - 20001:27017
    volumes:
      - ./data/shardsvr1_1:/data/db
      - /etc/timezone:/etc/timezone:ro
      - ./mongod_shardsvr.conf:/etc/mongod.conf:ro
      - ./mongodb.key:/mongodb.key
      - /usr/share/zoneinfo/Europe/Kiev:/etc/localtime:ro
  shardsvr1_2:
    container_name: shardsvr1_2
    image: mongo:7.0.4
    restart: always
    command: mongod --auth --replSet shard1_rs --config /etc/mongod.conf
    environment:
      MONGO_DATA_DIR: /data/db
      MONGO_LOG_DIR: /dev/null
    ports:
      - 20002:27017
    volumes:
      - /etc/timezone:/etc/timezone:ro
      - ./mongod_shardsvr.conf:/etc/mongod.conf:ro
      - ./mongodb.key:/mongodb.key
      - /usr/share/zoneinfo/Europe/Kiev:/etc/localtime:ro
      - ./data/shardsvr1_2:/data/db
  shardsvr1_3:
    container_name: shardsvr1_3
    image: mongo:7.0.4
    restart: always
    command: mongod --auth --replSet shard1_rs --config /etc/mongod.conf
    environment:
      MONGO_DATA_DIR: /data/db
      MONGO_LOG_DIR: /dev/null
    ports:
      - 20003:27017
    volumes:
      - /etc/timezone:/etc/timezone:ro
      - ./mongod_shardsvr.conf:/etc/mongod.conf:ro
      - ./mongodb.key:/mongodb.key
      - /usr/share/zoneinfo/Europe/Kiev:/etc/localtime:ro
      - ./data/shardsvr1_3:/data/db
