version: '3.1'
services:
  zabbix-agent:
    image: zabbix/zabbix-agent2:latest
    privileged: true
    network_mode: "host"
    restart: always
    user: "0:0"
    environment:
      - ZBX_SERVER_HOST=192.168.88.100
    ports:
      - 10050:10050
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./data/zabbix-agent:/etc/zabbix/zabbix_agentd.d
