version: '3'

networks:
  nextcloud:
    external: false
  public:
    external: true

volumes:
  nextcloud_app:
  nextcloud_data:
  nextcloud_redis:
  nextcloud_mariadb:

services:
  nextcloud:
    image: nextcloud:stable
    container_name: nextcloud
    hostname: nextcloud
    restart: unless-stopped
    networks:
      - nextcloud
      - public
    depends_on:
      - mariadb
      - redis
    volumes:
      - nextcloud_app:/var/www/html
      - nextcloud_data:/var/www/html/data
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
    environment:
      - MYSQL_DB=nextcloud_db
      - MYSQL_USER=nextcloud_db_user
      - MYSQL_PASSWORD=DB_PASSWORD
      - MYSQL_HOST=mariadb
      - REDIS_HOST=redis
      - REDIS_HOST_PORT=6379
      - SMTP_HOST=smtp.mail.com
      - SMTP_SECURE=tls
      - SMTP_PORT=465
      - SMTP_NAME=no-reply@mail.com
      - SMTP_PASSWORD=MAIL_PASSWORD
      - MAIL_FROM_ADDRESS=no-reply@mail.com
      - TRUSTED_PROXIES=10.0.0.0/8
      - OVERWRITEPROTOCOL=https
      - OVERWRITECLIURL=https://nextcloud.example.com
      - OVERWRITEHOST=nextcloud.example.com
      - PHP_MEMORY_LIMIT=2G
      - PHP_UPLOAD_LIMIT=16G
    deploy:
      mode: replicated
      replicas: 1
      labels:
        - "traefik.enable=true"
        - "traefik.docker.network=public"

        - "traefik.http.routers.nextcloud-https.rule=Host(`nextcloud.example.com`)"
        - "traefik.http.routers.nextcloud-https.entrypoints=https"
        - "traefik.http.routers.nextcloud-https.tls=true"
        - "traefik.http.routers.nextcloud-https.service=nextcloud"
        - "traefik.http.routers.nextcloud-https.middlewares=nextcloud-dav,nextcloud-headers"
        - "traefik.http.middlewares.nextcloud-dav.replacepathregex.regex=^/.well-known/ca(l|rd)dav"
        - "traefik.http.middlewares.nextcloud-dav.replacepathregex.replacement=/remote.php/dav/"
        - "traefik.http.middlewares.nextcloud-headers.headers.customFrameOptionsValue=SAMEORIGIN"
        - "traefik.http.middlewares.nextcloud-headers.headers.framedeny=true"
        - "traefik.http.middlewares.nextcloud-headers.headers.sslredirect=true"
        - "traefik.http.middlewares.nextcloud-headers.headers.stsIncludeSubdomains=true"
        - "traefik.http.middlewares.nextcloud-headers.headers.stsPreload=true"
        - "traefik.http.middlewares.nextcloud-headers.headers.stsSeconds=15552000"
        - "traefik.http.services.nextcloud.loadbalancer.server.port=80"

  cron:
      image: nextcloud:stable
      container_name: cron_nextcloud
      hostname: cron_nextcloud
      depends_on:
      - mariadb
      - redis
      - nextcloud
      volumes:
        - nextcloud_app:/var/www/html
        - nextcloud_data:/var/www/html/data
        - /etc/timezone:/etc/timezone:ro
        - /etc/localtime:/etc/localtime:ro
      entrypoint: /cron.sh
      networks:
        - nextcloud

  mariadb:
    image: mariadb
    container_name: mariadb_nextcloud
    hostname: mariadb_nextcloud
    restart: unless-stopped
    command: --transaction-isolation=READ-COMMITTED --binlog-format=ROW
    environment:
       - MARIADB_ROOT_PASSWORD=DB_ROOT_PASSWORD
       - MARIADB_USER=nextcloud_db_user
       - MARIADB_PASSWORD=DB_PASSWORD
       - MARIADB_DATABASE=nextcloud_db
    networks:
       - nextcloud
    volumes:
       - nextcloud_mariadb:/var/lib/mysql
       - /etc/timezone:/etc/timezone:ro
       - /etc/localtime:/etc/localtime:ro
    deploy:
      mode: replicated
      replicas: 1
  
  redis:
    image: redis
    container_name: redis
    hostname: redis
    restart: unless-stopped
    command: --save 60 1 --loglevel warning
    networks:
      - nextcloud
    volumes:
      - nextcloud_redis:/data
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
    deploy:
      mode: replicated
      replicas: 1
    