version: "3.1"
services:
  portainer:
    image: portainer/portainer-ce:2.9.3-alpine
    restart: always
    ports:
     - 127.0.0.1:9999:9000
     - 8000:8000
    command: -H unix:///var/run/docker.sock
    volumes:
     - /var/run/docker.sock:/var/run/docker.sock
     - ./data/portainer:/data


