version: "3.1"
services:
    myapp:
      build: 
        context: .
      container_name: myapp
      working_dir: /app
      restart: always
      environment:
        - VAR1=xxxxxxxxxx
      volumes:
        - /etc/localtime:/etc/localtime:ro
