version: "3.1"
services:
    dbx:
      image: mysql:8.0.22
      container_name: ${ZONE}-db
      working_dir: /app
      command: --default-authentication-plugin=mysql_native_password
      restart: always
      volumes:
        - ./data:/var/lib/mysql
        - ./srcdb:/docker-entrypoint-initdb.d
        - /etc/localtime:/etc/localtime:ro
      environment:
        MYSQL_ROOT_PASSWORD: rootStrong_password
        MYSQL_DATABASE: example_db
        MYSQL_USER: example_user
        MYSQL_PASSWORD: Strong_Password

    nginx:
      image: nginx:alpine
      container_name: ${ZONE}-nginx
      working_dir: /var/www/
      restart: always
      volumes:
          - ./src:/var/www/
          - /etc/nginx/ssl/example.crt:/etc/nginx/ssl/example.crt
          - /etc/nginx/ssl/example.key:/etc/nginx/ssl/example.key
          - ./default.conf:/etc/nginx/conf.d/default.conf
          - /etc/localtime:/etc/localtime:ro
      ports:
       - "127.0.0.1:${NGINX_HTTP_PORT}:443"

    app:
      build: .
      container_name: ${ZONE}-app
      working_dir: /var/www
      restart: always
      entrypoint: [ "bash", "-c", "php artisan config:cache && php artisan view:cache && php-fpm"]      
      volumes:
        - ./src:/var/www/
        - ./envx:/var/www/.env
        - /etc/localtime:/etc/localtime:ro

